/*
  ==============================================================================

    ViewConstants.h
    Created: 19 Jun 2014 7:23:25pm
    Author:  hsstraub

  ==============================================================================
*/

#pragma once

// General constants
#define STANDARDLABELHEIGTH 15

// Main window
#define DEFAULTMAINWINDOWWIDTH 868
#define DEFAULTMAINWINDOWHEIGHT 768
#define DEFAULTMAINWINDOWASPECT 1.13f

// Key set fields
#define TERPSTRAKEYSETVERTICALRIM 12
#define MINIMALTERPSTRAKEYSETAREAHEIGHT 30

#define OCTAVEBOARDTABHEIGHT 30

// Single key fields
#define TERPSTRASINGLEKEYFIELDRIMABOVE 24
#define TERPSTRASINGLEKEYFIELDRIMLEFT 16
#define TERPSTRASINGLEKEYFLDSIZE 50
#define TERPSTRASINGLEKEYFLDLINEWIDTH 2.0f
#define TERPSTRASELECTEDKEYFLDLINEWIDTH 3.0f
#define TERPSTRASINGLEKEYFLDMARGIN 1.5f
#define TERPSTRASINGLEKEYROTATIONANGLE -0.25f
#define TERPSTRASINGLEKEYCOLOURHIGHLIGHTEDALPHA 0.9f
#define TERPSTRASINGLEKEYCOLOURALPHA 0.8f
#define TERPSTRASINGLEKEYCOLOURUNSELECTEDMINIALPHA 0.6f

#define TERPSTRASINGLEKEYLABELSIZE 0.8333f;

// Edit area
#define NOTEASSIGNSUBWINTOP 44
#define NOTEASSIGNSUBWINHEIGHT 352
#define MAPPINGSUBWINTOP 88
#define MAPPINGSUBWINHEIGHT 128

#define MINIMALCURVESAREAHEIGHT 30
#define MINIMALCURVESAREAWIDTH 100
#define CURVETABRIMABOVE 8
#define BEAMTABLERIMABOVE 8
