/*
  ==============================================================================

    ViewConstants.h
    Created: 19 Jun 2014 7:23:25pm
    Author:  hsstraub

  ==============================================================================
*/

#ifndef VIEWCONSTANTS_H_INCLUDED
#define VIEWCONSTANTS_H_INCLUDED

// General constants
#define STANDARDLABELHEIGTH 15

// Main window
#define DEFAULTMAINWINDOWWIDTH 928
#define DEFAULTMAINWINDOWHEIGHT 768

#define MAINWINDOWFIRSTCOLPOS 20

// Key set fields
#define TERPSTRAKEYSETFLDFIRSTYPOS -16
#define DEFAULTTERPSTRAKEYSETWIDTH 207
#define DEFAULTTERPSTRAKEYSETHEIGHT 214
#define DEFAULTTERPSTRAKEYSETXINCREMENT 149
#define MINIMALTERPSTRAKEYSETAREAHEIGHT 30

#define OCTAVEBOARDTABHEIGHT 30

// Single key fields
#define TERPSTRASINGLEKEYFIELDRIMABOVE 24
#define TERPSTRASINGLEKEYFIELDRIMLEFT 16
#define TERPSTRASINGLEKEYFLDSIZE 55
#define TERPSTRASINGLEKEYFLDLINEWIDTH 2.0f
#define TERPSTRASELECTEDKEYFLDLINEWIDTH 3.0f
#define TERPSTRASINGLEKEYFLDMARGIN 1.5f
#define TERPSTRASINGLEKEYROTATIONANGLE -0.25f
#define TERPSTRASINGLEKEYCOLOURALPHA 0.8f
#define TERPSTRASINGLEKEYCOLOURUNSELECTEDMINIALPHA 0.3f

// Edit area

#define NOTEASSIGNSUBWINTOP 44
#define NOTEASSIGNSUBWINHEIGHT 352
#define MAPPINGSUBWINTOP 88
#define MAPPINGSUBWINHEIGHT 128

#endif  // VIEWCONSTANTS_H_INCLUDED
